version: "3.8"

services:
  db:
    image: postgres:15
    container_name: bhp_postgres_db
    environment:
      POSTGRES_USER: bhp_admin
      POSTGRES_PASSWORD: tajnehaslo123
      POSTGRES_DB: bhp_auditor_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
